### ISSUE TITLE
Making sqla_yaml_fixtures work in Python 2

### ISSUE THREAD

**Issue by justb4** [schettino72/sqla_yaml_fixtures#1]
Found `sqla_yaml_fixtures` a very useful tool! Using Python 2.7 I stumbled on `lru_cache` not being available. Via [backports.functools_lru_cache](https://pypi.python.org/pypi/backports.functools_lru_cache) I could made it work. Yes, we should all move to Python 3 I know...I have the changes in [my fork](https://github.com/justb4/sqla_yaml_fixtures/blob/master/sqla_yaml_fixtures.py) and can make a PR.

**Comment by schettino72** [comment]
Sincerely I dont want to spend my time supporting python 2, but I understand you... 

I could give you permission to this repository if you are willing to keep python2 compatibility. But then I would require you to make sure installation and everything works well on python2... And maybe setup some continuous integration system.

Or just keep your fork... its open source. I could add link to your fork in the README file.

**Comment by justb4** [comment]
I can add to your repo via PRs, this won't require direct access plus you can always review a PR. I see you started using `Shippable` and will try to add/build with Python 2 CI there.

**Comment by schettino72** [comment]
What I mean is that I expect you to maintain Python2 compatibility. That includes responding to user issues and maybe merging requests.

I will not look into python2, so if you are not willing to step up as a maintainer better not support it at all.

**Comment by justb4** [comment]
Aha, that is ok, make me maintainer, I'll accept invite. Now trying to get Shippable CI working for Python 2...found what I think interesting bug.. will open.

**Comment by schettino72** [comment]
Just realized that  on python2 and python <3.6 you will have a problem because YAML will not keep the order the models were defined...

**Comment by justb4** [comment]
At the same time as your comment I was filing this issue #2. See also last sentence there.
