### ISSUE TITLE
Using back_populates to create nested values

### ISSUE THREAD

**Issue by salfield** [schettino72/sqla_yaml_fixtures#7]
Having reviewed (and briefly tested) the way nested fixtures are created I'm not sure that using `back_populates` columns to create nested values is too wise. Are you aware that columns with `backref`will also add the `back_populates` column? In this case if the nested object has a constructor and it doesn't take the parent object as a parameter it will then fail, as we are passing an unknown parameter? Thus, it means that the constructor needs to be structured according to the needs of the yaml fixtures with might interfere with general application structure.

What is wrong with always creating the nested values through a call to `_create_obj`?

Please feel free to close or ignore this, if I have misunderstood something...I'm not too confident in my understanding of sqlalchemy internals.

**Comment by schettino72** [comment]
I understand your problem, but there are cases where the nested element **needs** a reference to its parent. `sqla_yaml_fixtures` tries to be smart... but also relies on how you structure your yaml file. 

For example `back_populates` is required when you have a one-to-many relation and your yaml contains the *many* as nested objects.

There are several examples in the test file. can you provide a concrete example where you are having problems?
