### ISSUE TITLE
test_cmd fails on python 2.7

### ISSUE THREAD

**Issue by schettino72** [schettino72/sqla_yaml_fixtures#9]
Sorry, did a quick release without fixing this...

I guess the problem affects only tests. 
Not sure the problem is a less powerful `importlib` on python 2.7 or the differences in importing...

**Comment by justb4** [comment]
First quick analysis (not behind computer now): `__init.py__`  may be required for Py2 import  of sample.py module. See also http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html

**Comment by schettino72** [comment]
oh. of course... i was thinking on py2.7 already supported that.

**Comment by justb4** [comment]
Tests now all succeed but code coverage went down (it was  100% before I thought). Possibly since `sample.py` is counted in now (?). Will add more `asserts` to `test_cmd.py` as to completely cover `sample.py`.

**Comment by schettino72** [comment]
> Possibly since sample.py is counted in now (?)

No. It really is not 100% any more. `test_cmd.py` just test a simple case. Not all options from the command line.

Sincerely testing all command line options is too much for me, I would not bother about it. But of course welcome if you want.

By the way, have you tried to use the command line? What do you think? What is really needed is to mention it in the docs...

**Comment by schettino72** [comment]
oh. just checked the coverage report. 2 problems:

- tests execute using subprocess
- should install the package with `-e` flag. right now source is taken from 2 different locations.

**Comment by justb4** [comment]
Ok. No I am just adding more queries/asserts to cover `sample.py`. Makes the cmd-result tests more complete anyway. 

Command line: Up to now I have used `sqla_yaml_fixtures` from within a Flask app via an upload/import service. I think the command line is very useful. A generic "export" command to a `.yaml` file as well, but is probably complex to make that generic.

**Comment by schettino72** [comment]
thanks
